version: '3'

services:
  grpc2http-gateway:
    image: qianxunclub/grpc2http-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - swagger.serverUrl=http://localhost:8080
      - grpc.endpoint.coding-app-project=dev.coding.oa.com:9902